year = c(5,10,15,20,25,30,32)
socialSecurityCost = c(17.1,29.6,63.6,117.1,186.4,246.5,285.1)
USA = data.frame(socialSecurityCost,year)
?plot()
par(mfrow = c(1,1))
plot(year, socialSecurityCost, xlab = 'Year-1960', ylab = 'Social Securtiy Cost ($Billion)')
abline(b = 10.2845, a = -66.2249, lwd = 5, col = 'red')
USALR = lm(formula = socialSecurityCost~year, data = USA)
summary(USALR)
abline(lm(formula = socialSecurityCost~year, data = USA),lwd = 3, col = 'blue')

?data.frame()
add = lm(formula = socialSecurityCost~year, data = USA)
?lm()
summary(add)
sum(year)
sum(socialSecurityCost^2)
sum(year^2)
sum(year*socialSecurityCost)
par(mfrow = c(1,1))
plot(year,residuals(add), xlab = 'Year-1960', ylab = 'Residuals')

View(Auto)
dim(Auto)
?pairs()

#Question 8
fileName = "Auto.txt"
defaultDataDir = "/Users/kyle/Documents/LSE-PKU/tutorial_class/Extra Data"
fileLocation = file.path(defaultDataDir, fileName)
Auto = read.table(file = fileLocation, header = T, sep = '', na.strings = '?')
Auto_nonNA = na.omit(Auto)
View(Auto)
pairs(mpg~., data = Auto_nonNA)
attach(Auto_nonNA)
cor(Auto_nonNA[1:8])

autoMLR = lm(formula = mpg~. -name, data = Auto_nonNA)
summary(autoMLR)
autoMLR_sqrt = lm(formula = mpg~sqrt(cylinders) + sqrt(displacement) + sqrt(horsepower) + sqrt(weight) + sqrt(acceleration) + sqrt(year) + sqrt(origin), data = Auto_nonNA)
summary(autoMLR_sqrt)
autoMLR_log = lm(formula = mpg~log(cylinders) + log(displacement) + log(horsepower) + log(weight) + log(acceleration) + log(year) + log(origin), data = Auto_nonNA)
summary(autoMLR_log)
autoMLR_squa = lm(formula = mpg~cylinders^2 + displacement^2 + horsepower^2 + weight^2 + acceleration^2 + year^2 + origin^2, data = Auto_nonNA)
summary(autoMLR_squa)

par(mfrow = c(2,2))
plot(autoMLR)
plot(autoMLR_log)
plot(autoMLR_sqrt)
plot(autoMLR_squa)
